### ISSUE TITLE
startOffset for second star

### ISSUE THREAD

**Issue by ocozalp** [Xiot/xiot.github.io#1]
https://github.com/Xiot/xiot.github.io/blob/5d92fd5a6bbe5d8f5f602235653cb6728fd7a688/view.js#L269

Start offset for the first star should be the offset for the second star. 

I realized because I was so sleepy after solving part 1 today and if I solve the part 2 this morning, the duration for part 2 can be shorter than part 1 :)

**Comment by Xiot** [comment]
Ya, I was thinking about that as I was contimplating going to sleep after banging my head against part 2.
I'll fix it up

**Comment by Xiot** [comment]
Implemented.
