### ISSUE TITLE
Fix - Medals for Day 

### ISSUE THREAD

**Issue by ocozalp** [Xiot/xiot.github.io#2]
https://github.com/Xiot/xiot.github.io/blob/5d44810ad87216ced557d2f4a559056b0c9730e1/view.js#L279

Apparently JS executes this line starting from the rightmost statement (like below)

```js
return isPosition(day.star1, position) ? 1 : (0 + isPosition(day.star2, position) ? 1 : 0)
```

Should be 

```js
return (isPosition(day.star1, position) ? 1 : 0) + (isPosition(day.star2, position) ? 1 : 0)
```

**Comment by Xiot** [comment]
What day was this affecting ?

**Comment by ocozalp** [comment]
Everyone. Consider Sepandar's medals, he has 2 golden stars today but total shows 1.

**Comment by Xiot** [comment]
pushed fix
